import alias from './src/alias';
import audio from './src/audio';
import center from './src/center';
import debug from './src/debug';
import jump from './src/jump';
import left from './src/left';
import right from './src/right';
import scene from './src/scene';
import sound from './src/sound';